### ISSUE TITLE
How's a poor guy track down imported stuff?

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#134]
1. What is the type `Params` [here](https://github.com/labrad/scalabrad-web/commit/f2626abed4a680a50060c87d0d25791f2beae8ff#diff-ddbcd08cf6b2115bac89ff33adf3a63fR20)?
2. How could I have discovered the answer to #1 on my own? Eclipse is no help.
3. If there's no good answer to #2, should `._` imports be banned in our projects given that Eclipse doesn't help much with Scala?

**Comment by maffoo** [comment]
In Eclipse, double click on `Params` to highlight the word, then press F3 to jump to definition. This takes you to the `package.scala` where the type definition is located (`Params` is just an alias for `Either[Seq[JsValue], Map[String, JsValue]]` since JSON rpc calls can specifiy positional parameters or named parameters when making a call). Jump to definition works for lots of things, classes, methods, etc. It's often a good thing to try when confronted with a name you don't know.

As for point 3, `Params` is not being brought in through a wildcard import, rather it is defined in the `org.labrad.browser.jsonrpc` package object, and so it's visible everywhere within that package without an import.

I don't think banning wildcard imports in scala is practical, but we should of course try to be judicious with their use.

**Comment by DanielSank** [comment]
> In Eclipse, double click on Params to highlight the word, then press F3 to jump to definition.

Nice.

> As for point 3, Params is not being brought in through a wildcard import, rather it is defined in the org.labrad.browser.jsonrpc package object, and so it's visible everywhere within that package without an import.

I don't even... I looked at this file several times using ctl-F and did not see the definition. Sigh.

> I don't think banning wildcard imports in scala is practical, but we should of course try to be judicious with their use.

Ok.
