### ISSUE TITLE
Why are there unused variables in SyncMethodHandler?

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#135]
Here's a code excerpt from JsonRpc.scala

``` scala
trait Handler {
  def call(params: Params)(implicit ec: ExecutionContext): Future[JsValue]

  val methodName: String
  val paramNames: Seq[String]

  def checkArgs(args: Params): Unit = {
    args match {
      case Left(args) =>
        if (args.size > paramNames.size) {
          throw JsonRpcError.invalidParams(JsString(s"expected ${paramNames.size} but got ${args.size}"))
        }

      case Right(kwArgs) =>
        val invalids = kwArgs.keys.toSet -- paramNames
        if (invalids.nonEmpty) {
          throw JsonRpcError.invalidParams(json"""{ unexpected: [..${invalids.toSeq.sorted}] }""")
        }
    }
  }
}


class SyncMethodHandler[B](
  val methodName: String,
  val paramNames: Seq[String]
  invoke: Params => B,
  writer: Writes[B]
) extends Handler {
  def call(args: Params)(implicit ec: ExecutionContext): Future[JsValue] = {
    Future {
      checkArgs(args)
      val result = invoke(args)
      writer.writes(result)
    }
  }
}
```

What's with the `val  methodName` and `val paramNames` in the constructor of `SyncMethodHandler?
1. Neither of those are referenced in the class body. Couldn't they be in `Handler`?
2. What is the meaning of `val` showing up in the class constructor?

**Comment by maffoo** [comment]
`methodNames` and `paramNames` _are_ defined in the `Handler` trait, but they're abstract since no values are specified. This means that in order to implement the trait, a class must have vals with those names. `paramNames` is used in the `checkArgs` method; `methodName` is not actually used, but I included it thinking that it could be helpful for things like error messages.

Adding `val` in front of a class parameter makes that parameter a publicly-accessible member of the class. This is just convenient shorthand instead of having to create a separate public member and assign the constructor parameter to it. By making `methodName` and `paramName` public vals we fulfill the requirements of the `Handler` trait for these two required abstract members.

**Comment by DanielSank** [comment]
> Adding val in front of a class parameter makes that parameter a publicly-accessible member of the class. 

Oh.
