### ISSUE TITLE
Chrome link preview covers last row

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#147]
The link preview on Chrome (showing the link in the bottom left corner) covers up the last row of text. This is particularly noticeable on the Node page, where it covers up the name of the Serial Server.

**Comment by maffoo** [comment]
@jwenner, I've noticed this, but if you actually mouse over the link preview, it moves out of the way, so it doesn't cover a link you are actually trying to click. Does that make this less of a problem for you?

**Comment by jwenner** [comment]
Maybe less of a problem, but still not negated. Would it be possible to add one blank line at the bottom of the page (likely outside the table) to allow for anything like this bar?

**Comment by DanielSank** [comment]
I agree that this is annoying and has confused me several times. Definitely not a priority IMHO though.

**Comment by adamcw** [comment]
There is no way to disable the status bar in Google Chrome.

The only "fix" for this issue would be to add a fixed footer at the bottom of the page, but that's essentially just permanently covering whatever is at the bottom of the screen, instead of temporarily.

You can't just add padding to the bottom of the page, because that doesn't stop the issue occurring when the page is longer than the window, as the padding wont even be on the page.

I'm marking this wont-fix, but perhaps it is an argument to increase browser support to at least Firefox (Issue #93) so users have some flexibility to work around browser features (such as this status bar) that they don't like.

**Comment by jwenner** [comment]
@adamcw, what I was imagining was just adding a blank line at the bottom. While I agree that this wouldn't fix if the page is longer than the window, I (and probably 99.999%+ of users) am used to scrolling down in such a case. The real issue is that, for the last line, I can't scroll down to make the last line always visible.

**Comment by adamcw** [comment]
@jwenner I'm not sure I like implementing a footer for the sake of a browser feature, but I see your point. I'll make a PR with the change and see what the others think.
