### ISSUE TITLE
can't access my dev-mode server from my laptop

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#166]
I get the error message in the console: bundle.js:
`16476 WebSocket connection to 'ws://localhost:7667/api/socket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

**Comment by maffoo** [comment]
It's trying to make the websocket to localhost, but the server is running on a different host (your workstation). I think you'll need to do two things to make this work:
- Change the `window.apiHost` in the gulpfile to use the actual hostname of your workstation, instead of localhost (https://github.com/labrad/scalabrad-web/blob/master/client-js/gulpfile.js#L231).
- Tell the scala server to accept external connections when you launch it on your workstation: `$ sbt "server/run --host=0.0.0.0"` (`host` defaults to `127.0.0.1` so that only local connections are accepted).

**Comment by joshm-3b6b58** [comment]
Awesome, thanks!
