### ISSUE TITLE
How should users with Trust 14.04 get around the Java 8 dependence?

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#18]
I just tried using the sbt build files in `/project` to start up an independent project and when I tried to drop into sbt from the root directory I got the following:

```
[error] java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0
[error] Use 'last' for the full log.
```

This appears to be due to not having Java 8 set up. Unfortunately JDK-8 is not available on Trusty 14.04 (it is on 14.10 but the current LTS is 14.04). Keeping in mind that I'm not using a Goobuntu computer, how should I get around this issue?

I've looked at some of the usual resources but there doesn't seem to be a canonical way to do this short of compiling it from source.

Do we have a recommended way to set up JDK-8 on Trust 14.04? If not, can I use this project with Java 7?

**Comment by DanielSank** [comment]
A good starting point would be to understand what in the build definition sets the requirement on JDK-8. So far I don't get it.

**Comment by maffoo** [comment]
It's actually very easy to install java 8 without a system package. Basically just download the .tar.gz archive from [here](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) and unpack it somewhere like `~/lib/` (then you don't even have to be root). Then put the bin directory `~/lib/jdk1.8.0_51/bin` on your path. Make sure it's the first thing on the path so it gets picked up before any system java.

As for what sets the java 8 requirement, it's basically the play libraries (and others from Typesafe like the config library in your error message) that were compiled to the java 8 classfile format.

**Comment by DanielSank** [comment]
This is funny. I never even considered using Oracles libs >.<

**Comment by DanielSank** [comment]
> Then put the bin directory ~/lib/jdk1.8.0_51/bin on your path. Make sure it's the first thing on the path so it gets picked up before any system java.

Perhaps we should distribute a `work_on_this_project.sh` which modifies the path. I'm not a big fan of changing things in my global profile or bashrc.

**Comment by maffoo** [comment]
Here's a link to the webupd8 instructions for installing oracle java 8 via repository, which makes it easier to stay up to date: http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

Re: a shell file to update the path, I don't think there's a good way to do this because people will have different systems, e.g. goobuntu has various javas preinstalled, some might use webupd8, others will install from the tar.gz as suggested above, but may choose a different path, etc. I think the best we can do is mention in the README that this requires java 8 because play and trust our users to figure out how to do that in their environment.

Either that, or we ditch the dependency on play, which I'm not entirely averse to doing...
