### ISSUE TITLE
Empty sealed trait Message

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#20]
In `Protocol.scala`, what's the point of the empty sealed trait `Message`?

**Comment by maffoo** [comment]
It's empty because it's just a marker type, a way to group a set of types that don't share any methods or data but are just in the group (e.g. they're all messages). It's sealed because the set of messages is not extensible, e.g. you can't define other implementations of message outside this file. This allows the compiler to check exhaustivity of pattern matches because it knows all the possible subclasses of Message.
