### ISSUE TITLE
How is the index page served?

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#27]
I would like to understand how routing works in play and scalabrad-web. Looking through the routes file, it looks like `/` maps to the [BrowserController](https://github.com/labrad/scalabrad-web/blob/master/server/src/main/scala/org/labrad/browser/BrowserController.scala#L45) class. In that class there a line

``` scala
controllers.Assets.at(path="/public", file="index.html")
```

What is this line actually doing? Searching for index.html we find some funny business going on in `client-js/gulpfil.js`. It appears `index.html` is created at build time.

What the hell is going on?

**Comment by maffoo** [comment]
`index.html` exists at `client-js/app/index.html`, however the build system modifies it slightly for dev mode (since #25 got merged) or production mode. In dev mode, the `websocket-url` gulp task copies `index.html` from `app/` into `.tmp/` with a single modification to add a script that sets the url to use for connecting to the scala backend for websocket connections. The browserSync server used for dev mode then serves static files from the `.tmp/` and `app/` directories (in that order, so that modified versions of files in `.tmp/` take priority over the raw files in `app/`).

When we create the production version of the app (the `default` task which runs when you just call `gulp` with no args on the command line) we copy `index.html` to the `dist/` directory along with all the other build outputs. There are more modifications to the file in this case, like changing the `elements.html` link to point to the vulcanized version, minifying and stripping comments, and so on. The full set of static files to be served then lives in `client-js/dist/`.

Now, the scala build defines a 'resource generator' which is a mechanism for running code to generate resource files as though they were static files in `server/src/main/resources/` (see [here](https://github.com/labrad/scalabrad-web/blob/master/build.sbt#L41)). This copies the files from `client-js/dist/` to a directory defined by the setting `resourceManaged in Assets`, that is, the directory set up for managed resources built by play's asset pipeline (we're not using the asset pipeline per se, just putting the files generated by our js project in the directory it defines). These files are then bundled as resources with the built scala application, and in particular they are accessible to the asset controller to serve under the `/public` path.

This is by no means the final solution, but that's how it works right now.
