### ISSUE TITLE
Datapoints don't display in Chrome Remote Desktop

### ISSUE THREAD

**Issue by zchen088** [labrad/scalabrad-web#319]
Recently, when I use the grapher through Chrome Remote Desktop, it will draw the frame for the dataset but not any of the data. Chris said this started happening to him as well as of a few days ago and Amit confirms he also has this issue.

**Comment by maffoo** [comment]
WebGL is not enabled by default when using remote desktop, and that might be the issue you're having. @joshmutus figured out how to fix this in #241:

- Open Google Chrome.
- Type `chrome://flags` in the address bar.
- Enable the setting `Override software rendering list`.
- Restart your browser.

Please try that and see if it fixes things for you. I'll also add a note in the readme, since this has come up several times in the past.

**Comment by zchen088** [comment]
Cool, seems to work now.
