### ISSUE TITLE
Can this be installed on Windows?

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#48]
Or will node screw everything up?

**Comment by maffoo** [comment]
I don't know the status of node on windows; it probably works with caveats. Since we're using jspm and bower for dependencies, we don't need really deep node package hierarchies, so I suspect it would be fine. This is all just a question of development, though; for actual _installation_ just to use this, node is not required (we need to publish packages for this though).

I heard anecdotally from Christopher Reilly that he got things working on windows, but had to jump through some hoops with node. I'll ask him to weigh in here.

**Comment by creilly** [comment]
I'll start by admitting that I have no idea if what is described below is the only way to do this.

The recipe I've found is to use an older version of node, say 0.12.17. Then follow the instructions described on the github wiki (npm install -> jspm install -> bower install -> gulp serve). Note the npm install command will throw a bunch of errors. Gulp will complain about "node_modules is not a known command" or something like that. Then go to gulpfile.js and edit line 62 from:

``` javascript
  var cmd = 'node_modules/.bin/jspm bundle-sfx scripts/app .tmp/scripts/bundle.js --skip-source-maps';
```

to

``` javascript
  var cmd = 'jspm bundle-sfx scripts/app .tmp/scripts/bundle.js --skip-source-maps';
```

i.e. remove the "node_modules/.bin/" prefix.

Hope that works.

**Comment by joshm-3b6b58** [comment]
Thanks @creilly 

@DanielSank you mentioned you were interested in trying this out. Do you want to give this a shot on ReadHeat? If it works we can add this to the readme and mark as resolved.

**Comment by maffoo** [comment]
Just tried this and it now works fine to develop on windows. The changes to our workflow to use `npm run jspm install` and corresponding changes in the gulpfile to use this way of invoking `jspm` seem to have fixed things.
