### ISSUE TITLE
What does "tray" mean?

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#78]
In the file tree, we have `server/src/main/scala/org/labrad/tray`. What does "tray" mean?

**Comment by DanielSank** [comment]
@maffoo ?

**Comment by maffoo** [comment]
The tray package puts an icon in the system tray that when clicked will launch a web browser and load the scalabrad-web interface. I wrote this with a use case in mind where the browser would be run on your local machine (by double-clicking a jar, say) and then would itself connect to remote labrad, just like you do from, say, ipython. As opposed to running the web interface on a server with a well-known public DNS name that you connect to. The advantage of the former is that you don't have to set up a server (including certs etc. for security), you just need to have labrad going. The advantage of having a real server, on the other hand, is that you can share URLs with people, say pointing to different data sets. So basically, this is an experiment, not sure what we'll do with it in the long run. I will say it's a little awkward to have the tray package work with play, since play wants to do things one way, and it is much more geared toward running a server than running a desktop app.
